- id: poetry-check
  name: poetry-check
  description: run poetry check to validate config
  entry: poetry check
  language: python
  language_version: python3
  pass_filenames: false
  files: ^pyproject.toml$